/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author Charly Cimino
 */
public class Pantalla extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Pantalla.class.getName());

    /**
     * Creates new form Pantalla
     */
    public Pantalla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dkpPantalla = new javax.swing.JDesktopPane();
        psw1 = new javax.swing.JPasswordField();
        psw2 = new javax.swing.JPasswordField();
        psw3 = new javax.swing.JPasswordField();
        lbMagnitud = new javax.swing.JLabel();
        lbTrofeo = new javax.swing.JLabel();
        btnRevelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        psw1.setText("jPasswordField1");

        psw2.setText("jPasswordField1");

        psw3.setText("jPasswordField1");

        lbMagnitud.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lbMagnitud.setText("escribe 3 digitos");

        lbTrofeo.setBackground(new java.awt.Color(153, 153, 0));
        lbTrofeo.setForeground(new java.awt.Color(255, 204, 51));
        lbTrofeo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTrofeo.setIcon(new javax.swing.ImageIcon("E:\\Descargas Disco Local (A)\\Copia de seguridad\\Facultad 2\\ULP\\Laboratorio I\\tp2\\tp2-git-gui\\Tp2Laboratorio\\img\\Screenshot_1.png")); // NOI18N
        lbTrofeo.setText("TROFEO");
        lbTrofeo.setToolTipText("");

        btnRevelar.setText("REVELAR");

        dkpPantalla.setLayer(psw1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dkpPantalla.setLayer(psw2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dkpPantalla.setLayer(psw3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dkpPantalla.setLayer(lbMagnitud, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dkpPantalla.setLayer(lbTrofeo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dkpPantalla.setLayer(btnRevelar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout dkpPantallaLayout = new javax.swing.GroupLayout(dkpPantalla);
        dkpPantalla.setLayout(dkpPantallaLayout);
        dkpPantallaLayout.setHorizontalGroup(
            dkpPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dkpPantallaLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(dkpPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dkpPantallaLayout.createSequentialGroup()
                        .addComponent(psw1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(psw3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dkpPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnRevelar)
                        .addComponent(lbMagnitud)))
                .addGroup(dkpPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dkpPantallaLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(lbTrofeo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dkpPantallaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(psw2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        dkpPantallaLayout.setVerticalGroup(
            dkpPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dkpPantallaLayout.createSequentialGroup()
                .addGroup(dkpPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dkpPantallaLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(dkpPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(psw3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(psw2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dkpPantallaLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(psw1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(dkpPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMagnitud)
                    .addComponent(lbTrofeo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRevelar)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dkpPantalla)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dkpPantalla)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRevelar;
    private javax.swing.JDesktopPane dkpPantalla;
    private javax.swing.JLabel lbMagnitud;
    private javax.swing.JLabel lbTrofeo;
    private javax.swing.JPasswordField psw1;
    private javax.swing.JPasswordField psw2;
    private javax.swing.JPasswordField psw3;
    // End of variables declaration//GEN-END:variables
}
